export const CURRENCY_SYMBOL_MAPPER = {
    'ARS': '$',
    'USD': 'U$S',
    'BOB': 'Bs',
    'BRL': 'R$',
    'CLF': 'UF',
    'CLP': '$',
    'COP': '$',
    'CRC': '¢',
    'CUC': 'CUC',
    'CUP': '$',
    'DOP': '$',
    'EUR': '€',
    'GTQ': 'Q',
    'HNL': 'L',
    'MXN': '$',
    'NIO': 'C$',
    'PAB': 'B/.',
    'PEN': 'S/',
    'PYG': '₲',
    'UYU': '$',
    'VEF': 'Bs.',
    'VES': 'Bs.',
  };
  
  export const CONDITION_MAPPER = {
    'new': 'Nuevo',
    'used': 'Usado',
    'not_specified': 'No especificado',
  }